name: Build
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    name: Build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    timeout-minutes: 20
    steps:
      - name: Install moreutils
        run: sudo apt install moreutils

      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: lint
        run: shellcheck **/*.sh
